name: Tests

on:
  push:
  pull_request:
    branches:
      - "**:**" # PRs from forks have a prefix with `owner:`

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  xcode_tests:
    name: Tests (Xcode ${{ matrix.xcode }})
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "15.2"
            destination: "platform=iOS Simulator,name=iPhone 14,OS=17.2"

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app

      - name: Install Mint
        run: brew install mint

      - name: Cache Mint
        uses: actions/cache@v3
        with:
          path: ~/.mint
          key: ${{ runner.os }}-mint-xcode_${{ matrix.xcode }}-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-xcode_${{ matrix.xcode }}

      - run: mint bootstrap

      - name: Cache DerivedData
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-xcode_${{ matrix.xcode }}-derived_data-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-xcode_${{ matrix.xcode }}-derived_data-main
            ${{ runner.os }}-xcode_${{ matrix.xcode }}-derived_data-

      - name: Run Tests
        run: set -o pipefail && xcodebuild test -scheme Composed-Package -destination '${{ matrix.destination }}' 2>&1 | $(mint which xcbeautify) --renderer github-actions
